### PR TITLE
unicode (multibyte) characters are corrupted

### PR DESCRIPTION
**Pull request by aki77**
it's not safe to decode buffers to strings.
they may end part-way through a multi-byte character, hence the issue.

https://github.com/atom/atom/issues/4542

### CODE REVIEW

**Comment by tomoya** [comment]
Awesome :tada: 

Maybe fixes atom/atom#4268 too.

This is a very important issue. Because the file would have been broken by Atom. I believe it to be resolved soon.

**Comment by benogle** [comment]
Cool. 

We should pass the encoding in from atom. Can you make the encoding an option? We can fallback to utf8.

**Comment by tomoya** [comment]
Sounds cool!

**Comment by benogle** [comment]
Thanks for this. It is better, but there are still a bunch of other encoding issues. I will create another issue outlining them. Encodings are hard.

**Comment by aki77** [comment]
Thanks!

**Pull request merged**
