### PR TITLE
Fix a symlink search bug

### PR DESCRIPTION
**Pull request by m2q1n9**
Fix a bug when a symlink's target is a directory in the project may get duplicate search results

### CODE REVIEW

**Comment by benogle** [comment]
Can you give more information? Can you write a test?

**Comment by m2q1n9** [comment]
```bash

m2q1n9@mzqs-Air:~/github/scandal/spec/fixtures/many-files (bugfix-symlink[!?]) => l
total 76
-rw-r--r-- 1 m2q1n9 staff 4265 Mar 14 19:36 .file8_hidden.js
-rw-r--r-- 1 m2q1n9 staff   35 Mar 14 19:36 .gitignore
drwxr-xr-x 4 m2q1n9 staff  136 Mar 14 19:36 .root
-rw-r--r-- 1 m2q1n9 staff  392 Mar 14 19:36 binary-file.png
drwxr-xr-x 3 m2q1n9 staff  102 Mar 14 19:36 dir
-rw-r--r-- 1 m2q1n9 staff  651 Mar 19 12:05 file1.txt
-rw-r--r-- 1 m2q1n9 staff  600 Mar 19 12:05 file2.txt
-rw-r--r-- 1 m2q1n9 staff  679 Mar 19 12:05 file3.txt
-rw-r--r-- 1 m2q1n9 staff  719 Mar 19 12:05 file4_noext
-rw-r--r-- 1 m2q1n9 staff  506 Mar 19 12:05 file5_not_really_image.gif
-rw-r--r-- 1 m2q1n9 staff 1077 Mar 19 12:05 file6_contains_nonascii.dat
-rw-r--r-- 1 m2q1n9 staff 4321 Mar 19 12:05 file9_ignored_by_this_dir.txt
drwxr-xr-x 3 m2q1n9 staff  102 Mar 14 19:36 newdir
-rw-r--r-- 1 m2q1n9 staff  409 Mar 19 12:05 sample-end-newline.js
-rw-r--r-- 1 m2q1n9 staff  420 Mar 19 12:05 sample-with-windows-line-endings.js
-rw-r--r-- 1 m2q1n9 staff  408 Mar 19 12:05 sample.js
-rw-r--r-- 1 m2q1n9 staff   11 Mar 19 12:05 sample.txt
lrwxr-xr-x 1 m2q1n9 staff    5 Mar 19 12:19 symlink-to-directory -> ../..
lrwxr-xr-x 1 m2q1n9 staff    9 Mar 14 19:36 symlink-to-file1.txt -> file1.txt
-rw-r--r-- 1 m2q1n9 staff   26 Mar 19 12:05 thai.txt

```

create a link named symlink-to-directory to ../.. in spec/fixtures/many-files

then search some text in scandal project

for example, search:

```
return sort(Array.apply(this, arguments));
```

**Comment by izuzak** [comment]
Thanks, @m2q1n9. Could you convert that example into [a test](https://atom.io/docs/latest/hacking-atom-writing-specs) which passes with your proposed change and fails without your proposed change, and add that test to the pull request?

**Comment by m2q1n9** [comment]
it 'lists all non-hidden files with symlink follow', ->
```
binary-file.png
file1.txt
file2.txt
file3.txt
file4_noext
file5_not_really_image.gif
file6_contains_nonascii.dat
file9_ignored_by_this_dir.txt
sample-end-newline.js
sample-with-windows-line-endings.js
sample.js
sample.txt
symlink-to-file1.txt
thai.txt
dir/file7_ignorable.rb
newdir/deep_dir.js
symlink-to-directory/file7_ignorable.rb
```

@izuzak , test is added.
here `dir/file7_ignorable.rb` and `symlink-to-directory/file7_ignorable.rb` is duplicate.

**Comment by benogle** [comment]
Thanks. Sorry for the delay. It will be out in atom 191

**Comment by m2q1n9** [comment]
:sparkles:

**Pull request merged**
